/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasarminuscula;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.ArrayList;

/**
 *
 * @author mrmedfac9
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    int modo;  // 0 = Cambiar nombre  1 = Cambiar título 2 = Quitar espacios
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        //Inicializo el programa en el modo cambiar título
        setTitle("Transformar título");
        modo = 1; 
    }
    
    //Función para pasar de un array de caracteres a un string
    String getStringRepresentation(ArrayList<Character> list)
    {    
        StringBuilder builder = new StringBuilder(list.size());
        for(Character ch: list)
        {
            builder.append(ch);
        }
        return builder.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pegar = new javax.swing.JButton();
        transformar = new javax.swing.JButton();
        copiar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        programa = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        original = new javax.swing.JTextArea();
        transformado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 300));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Hecho por Rafael Medina Facal     ");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        pegar.setText("Pegar");
        pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegarActionPerformed(evt);
            }
        });
        jPanel2.add(pegar);

        transformar.setText("Transformar");
        transformar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformarActionPerformed(evt);
            }
        });
        jPanel2.add(transformar);

        copiar.setText("Copiar");
        copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarActionPerformed(evt);
            }
        });
        jPanel2.add(copiar);

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel2.add(limpiar);

        programa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título", "Nombre", "Espacios" }));
        programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programaActionPerformed(evt);
            }
        });
        jPanel2.add(programa);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        original.setColumns(20);
        original.setRows(5);
        jScrollPane1.setViewportView(original);

        jPanel3.add(jScrollPane1);
        jPanel3.add(transformado);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegarActionPerformed
        original.paste();
    }//GEN-LAST:event_pegarActionPerformed

    private void transformarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformarActionPerformed
        String texto;
        texto = original.getText();
        ArrayList<Character> textoModificaco = new ArrayList<Character>();
        
        if(modo == 0){
            boolean espacio = false;
            
            for(int i = 0; i < texto.length(); i++){
                
                espacio = texto.charAt(i) == ' ';
                
                if(espacio){
                    if(!textoModificaco.isEmpty() && texto.charAt(i + 1) != ' ' && texto.charAt(i + 1) != '\n'){
                        textoModificaco.add(texto.charAt(i));
                    }
                }
                else{
                    if(i == 0){
                        textoModificaco.add(texto.charAt(i));
                    }
                    else if(texto.charAt(i - 1) == ' '){
                        textoModificaco.add(texto.charAt(i));
                    }
                    else{
                        textoModificaco.add(texto.toLowerCase().charAt(i));
                    }
                }
            }
        }
        else if(modo == 1){
            boolean punto = false;
            boolean espacio = false;
            boolean espacioDelantero = false;
            
            for(int i = 0; i < texto.length(); i++){
                
                if(texto.charAt(i) == ' '){
                    espacio = true;
                    if(textoModificaco.isEmpty()){
                        espacioDelantero = true;
                    }
                }
                else{
                    espacio = false;
                }
                
                if(espacio){
                    if(!textoModificaco.isEmpty() && texto.charAt(i + 1) != ' ' && texto.charAt(i + 1) != '\n'){
                        textoModificaco.add(texto.charAt(i));
                    }
                }
                else{
                    if(espacioDelantero || i == 0 || (punto && texto.charAt(i) != ' ')){
                        textoModificaco.add(texto.charAt(i));
                        punto = false;
                        espacioDelantero = false;
                    }
                    else{
                        if(texto.charAt(i) == '.'){
                            punto = true;
                        }
                        textoModificaco.add(texto.toLowerCase().charAt(i));
                    }
                }
            }
        }
        else{
            boolean espacio = false;
            boolean tabulador = false;
            boolean espacioYtabulador = false;
            
            for(int i = 0; i < texto.length(); i++){
                espacio = texto.charAt(i) == ' ';
                
                tabulador = texto.charAt(i) == '\t';
                
                if(i != 0){
                    espacioYtabulador = (texto.charAt(i - 1) == ' ' && texto.charAt(i) == '\t') || (texto.charAt(i) == ' ' && texto.charAt(i - 1) == '\t');
                }
                
                if(!espacioYtabulador){
                    if(!tabulador){
                        if(espacio){
                            if(!textoModificaco.isEmpty() && texto.charAt(i + 1) != ' ' && texto.charAt(i + 1) != '\n'){
                                textoModificaco.add(texto.charAt(i));
                            }
                        }
                        else{
                            textoModificaco.add(texto.charAt(i));
                        }
                    }
                    else{
                        if(!textoModificaco.isEmpty() && texto.charAt(i + 1) != '\t' && texto.charAt(i + 1) != '\n'){
                            textoModificaco.add(' ');
                        }
                    }
                }
            }
        }
       
        texto = getStringRepresentation(textoModificaco);
        
        transformado.setText(texto);
    }//GEN-LAST:event_transformarActionPerformed

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarActionPerformed
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        String titulo;
        
        titulo = transformado.getText();
        StringSelection ss = new StringSelection(titulo);
        cb.setContents(ss, ss);
    }//GEN-LAST:event_copiarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        original.selectAll();
        original.replaceSelection("");
        transformado.selectAll();
        transformado.replaceSelection("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void programaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programaActionPerformed
        if(programa.getSelectedItem() == "Nombre"){
            setTitle("Transformar nombre");
            modo = 0;
        }
        else if(programa.getSelectedItem() == "Título"){
            setTitle("Transformar título");
            modo = 1;
        }
        else{
            setTitle("Quitar espacios");
            modo = 2;
        }
    }//GEN-LAST:event_programaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextArea original;
    private javax.swing.JButton pegar;
    private javax.swing.JComboBox<String> programa;
    private javax.swing.JTextField transformado;
    private javax.swing.JButton transformar;
    // End of variables declaration//GEN-END:variables
}
