/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasarminuscula;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author mrmedfac9
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    int modo;  // 0 = Cambiar nombre  1 = Cambiar título
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("Transformar nombre");
        modo = 0; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pegar = new javax.swing.JButton();
        transformar = new javax.swing.JButton();
        copiar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        cambiarModo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        original = new javax.swing.JTextArea();
        transformado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 300));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Hecho por Rafa Medina Facal     ");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout());

        pegar.setText("Pegar");
        pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegarActionPerformed(evt);
            }
        });
        jPanel2.add(pegar);

        transformar.setText("Transformar");
        transformar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformarActionPerformed(evt);
            }
        });
        jPanel2.add(transformar);

        copiar.setText("Copiar");
        copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarActionPerformed(evt);
            }
        });
        jPanel2.add(copiar);

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel2.add(limpiar);

        cambiarModo.setText("Cambiar a título");
        cambiarModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarModoActionPerformed(evt);
            }
        });
        jPanel2.add(cambiarModo);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        original.setColumns(20);
        original.setRows(5);
        jScrollPane1.setViewportView(original);

        jPanel3.add(jScrollPane1);
        jPanel3.add(transformado);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegarActionPerformed
        original.paste();
    }//GEN-LAST:event_pegarActionPerformed

    private void transformarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformarActionPerformed
        String titulo;
        titulo = original.getText();
        char tituloModificadoChar[] = new char [titulo.length()];
        
        if(modo == 0){
            for(int i = 0; i < titulo.length(); i++){
                if(i == 0){
                    tituloModificadoChar[i] = titulo.charAt(i);
                }
                else if(tituloModificadoChar[i - 1] == ' '){
                    tituloModificadoChar[i] = titulo.charAt(i);
                }
                else{
                    tituloModificadoChar[i] = titulo.toLowerCase().charAt(i);
                }
            }
        }
        else{
            boolean punto = false;
            
            for(int i = 0; i < titulo.length(); i++){
                if(i == 0 || (punto && titulo.charAt(i) != ' ')){
                    tituloModificadoChar[i] = titulo.charAt(i);
                    punto = false;
                }
                else{
                    if(titulo.charAt(i) == '.'){
                        punto = true;
                    }
                    
                    tituloModificadoChar[i] = titulo.toLowerCase().charAt(i);
                }
            }
        }
        
        titulo = String.valueOf(tituloModificadoChar);
        
        transformado.setText(titulo);
    }//GEN-LAST:event_transformarActionPerformed

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarActionPerformed
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        String titulo;
        
        titulo = transformado.getText();
        StringSelection ss = new StringSelection(titulo);
        cb.setContents(ss, ss);
    }//GEN-LAST:event_copiarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        original.selectAll();
        original.replaceSelection("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void cambiarModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarModoActionPerformed
        if(modo == 0){
            modo = 1;
            setTitle("Transformar título");
            cambiarModo.setText("Cambiar a nombre");
        }
        else{
            modo = 0;
            setTitle("Transformar nombre");
            cambiarModo.setText("Cambiar a título");
        }
    }//GEN-LAST:event_cambiarModoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarModo;
    private javax.swing.JButton copiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextArea original;
    private javax.swing.JButton pegar;
    private javax.swing.JTextField transformado;
    private javax.swing.JButton transformar;
    // End of variables declaration//GEN-END:variables
}
